pipeline {
    agent any

    stages {
        stage('build') {
            steps {
                sh """
                    docker build -t ruby_jenkins_app .
                """
            }
        }
        stage('run') {
            steps {
                sh """
                    docker run ruby_jenkins_app
                """
            }
        }
    }
}